# Dependencies
markdown:         kramdown


# Permalinks
permalink:        pretty

# Setup
title:            HMT documentation
tagline:          'Technical documentation for editors and contributors'
description:      'Evolving technical documentation for editors and contributors to the Homer Multitext project'
baseurl: '/hmt-docs/'


links:
  - title: HMT on github
    url: http://homermultitext.github.io/
    external: true
  - title: Prerequisite technologies
    url: /tech
  - title: Foundational work
    url: /dse
  - title: '"Total editing"'
    url: /totaled
  - title: Tips
    url: /tips
  - title: Github source for this site
    url: http://homermultitext.github.io/hmt-docs
    external: true
