# Dependencies
markdown:         kramdown


# Permalinks
permalink:        pretty

# Setup
title:            HMT documentation
tagline:          'Technical documentation for editors and contributors'
description:      'Evolving technical documentation for editors and contributors to the Homer Multitext project'
baseurl: '/hmt-docs/'


links:
  - title: Make a suggestion!
    url: /suggestions
  - title: Key references
    url: /references
  - title: HMT on github
    url: http://homermultitext.github.io/
    external: true
  - title: Github source for this site
    url: https://github.com/homermultitext/hmt-docs/
    external: true
